//==============================================================================
//  WARNING!!  This file is overwritten by the Block UI Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  D:\GZ\ProperyDraft\install\application\inheritProperty.cpp
//
//        This file was generated by the NX Block UI Styler
//        Created by: 15772
//              Version: NX 10
//              Date: 04-02-2019  (Format: mm-dd-yyyy)
//              Time: 22:01 (Format: hh-mm)
//
//==============================================================================

//==============================================================================
//  Purpose:  This TEMPLATE file contains C++ source to guide you in the
//  construction of your Block application dialog. The generation of your
//  dialog file (.dlx extension) is the first step towards dialog construction
//  within NX.  You must now create a NX Open application that
//  utilizes this file (.dlx).
//
//  The information in this file provides you with the following:
//
//  1.  Help on how to load and display your Block UI Styler dialog in NX
//      using APIs provided in NXOpen.BlockStyler namespace
//  2.  The empty callback methods (stubs) associated with your dialog items
//      have also been placed in this file. These empty methods have been
//      created simply to start you along with your coding requirements.
//      The method name, argument list and possible return values have already
//      been provided for you.
//==============================================================================

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include "inheritProperty.hpp"
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

//------------------------------------------------------------------------------
// Initialize static variables
//------------------------------------------------------------------------------
Session *(inheritProperty::theSession) = NULL;
UI *(inheritProperty::theUI) = NULL;
//------------------------------------------------------------------------------
// Constructor for NX Styler class
//------------------------------------------------------------------------------
inheritProperty::inheritProperty()
{
    try
    {
        // Initialize the NX Open C++ API environment
        inheritProperty::theSession = NXOpen::Session::GetSession();
        inheritProperty::theUI = UI::GetUI();
        theDlxFileName = "inheritProperty.dlx";
        theDialog = inheritProperty::theUI->CreateDialog(theDlxFileName);
        // Registration of callback functions
        theDialog->AddApplyHandler(make_callback(this, &inheritProperty::apply_cb));
        theDialog->AddOkHandler(make_callback(this, &inheritProperty::ok_cb));
        theDialog->AddUpdateHandler(make_callback(this, &inheritProperty::update_cb));
        theDialog->AddInitializeHandler(make_callback(this, &inheritProperty::initialize_cb));
        theDialog->AddDialogShownHandler(make_callback(this, &inheritProperty::dialogShown_cb));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        throw;
    }
}

//------------------------------------------------------------------------------
// Destructor for NX Styler class
//------------------------------------------------------------------------------
inheritProperty::~inheritProperty()
{
    if (theDialog != NULL)
    {
        delete theDialog;
        theDialog = NULL;
    }
}
//------------------------------- DIALOG LAUNCHING ---------------------------------
//
//    Before invoking this application one needs to open any part/empty part in NX
//    because of the behavior of the blocks.
//
//    Make sure the dlx file is in one of the following locations:
//        1.) From where NX session is launched
//        2.) $UGII_USER_DIR/application
//        3.) For released applications, using UGII_CUSTOM_DIRECTORY_FILE is highly
//            recommended. This variable is set to a full directory path to a file 
//            containing a list of root directories for all custom applications.
//            e.g., UGII_CUSTOM_DIRECTORY_FILE=$UGII_ROOT_DIR\menus\custom_dirs.dat
//
//    You can create the dialog using one of the following way:
//
//    1. USER EXIT
//
//        1) Create the Shared Library -- Refer "Block UI Styler programmer's guide"
//        2) Invoke the Shared Library through File->Execute->NX Open menu.
//
//------------------------------------------------------------------------------
void GZ_COPY_ATTR_Main()
{
    inheritProperty *theinheritProperty = NULL;
    try
    {
        theinheritProperty = new inheritProperty();
        // The following method shows the dialog immediately
        theinheritProperty->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        inheritProperty::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    if(theinheritProperty != NULL)
    {
        delete theinheritProperty;
        theinheritProperty = NULL;
    }
}

int inheritProperty::Show()
{
    try
    {
        theDialog->Show();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        inheritProperty::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//---------------------Block UI Styler Callback Functions--------------------------
//------------------------------------------------------------------------------

//------------------------------------------------------------------------------
//Callback Name: initialize_cb
//------------------------------------------------------------------------------
void inheritProperty::initialize_cb()
{
    try
    {
        group0 = dynamic_cast<NXOpen::BlockStyler::Group*>(theDialog->TopBlock()->FindBlock("group0"));
        bodySource = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodySource"));
        bodyTargets = dynamic_cast<NXOpen::BlockStyler::BodyCollector*>(theDialog->TopBlock()->FindBlock("bodyTargets"));
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        inheritProperty::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: dialogShown_cb
//This callback is executed just before the dialog launch. Thus any value set 
//here will take precedence and dialog will be launched showing that value. 
//------------------------------------------------------------------------------
void inheritProperty::dialogShown_cb()
{
    try
    {
        //---- Enter your callback code here -----
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        inheritProperty::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
}

//------------------------------------------------------------------------------
//Callback Name: apply_cb
//------------------------------------------------------------------------------
int inheritProperty::apply_cb()
{
    int errorCode = 0;
    try
    {
        //---- Enter your callback code here -----
		StlNXStringVector attrNames;
		StlNXStringVector attrValues;
		std::vector<NXOpen::TaggedObject* > objectS = bodySource->GetProperties()->GetTaggedObjectVector("SelectedObjects");
		std::vector<NXOpen::TaggedObject* > objectT = bodyTargets->GetProperties()->GetTaggedObjectVector("SelectedObjects");
		attrNames.push_back("材料类型");
		attrNames.push_back("材料名称");
		attrNames.push_back("材料编号");
		attrNames.push_back("规格");
		attrNames.push_back("材质");
		attrNames.push_back("密度");
		attrNames.push_back("单价");
		attrNames.push_back("供应商");
		attrNames.push_back("重量");
		attrNames.push_back("总价");
		attrNames.push_back("备注");
		attrNames.push_back("长度");
		attrNames.push_back("宽度");
		attrNames.push_back("面积");
		attrNames.push_back("已设零件标记");
		attrNames.push_back("输出材料编号");
		for(int jdx = 0; jdx < attrNames.size(); ++jdx )
		{
			char handle[UF_ATTR_MAX_STRING_BUFSIZE+1]="";
			int irc = USER_ask_obj_string_attr(objectS[0]->Tag(),(char*)attrNames[jdx].GetText(),handle);
			attrValues.push_back(handle);
		}
		for(int idx = 0; idx < objectT.size(); ++idx )
		{
			for(int jdx = 0; jdx < attrNames.size(); ++jdx )
			{
				Royal_set_obj_attr(objectT[idx]->Tag(),attrNames[jdx].GetText(),attrValues[jdx].GetText());
			}
		}
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        inheritProperty::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Callback Name: update_cb
//------------------------------------------------------------------------------
int inheritProperty::update_cb(NXOpen::BlockStyler::UIBlock* block)
{
    try
    {
        if(block == bodySource)
        {
        //---------Enter your code here-----------
        }
        else if(block == bodyTargets)
        {
        //---------Enter your code here-----------
        }
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        inheritProperty::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return 0;
}

//------------------------------------------------------------------------------
//Callback Name: ok_cb
//------------------------------------------------------------------------------
int inheritProperty::ok_cb()
{
    int errorCode = 0;
    try
    {
        errorCode = apply_cb();
    }
    catch(exception& ex)
    {
        //---- Enter your exception handling code here -----
        errorCode = 1;
        inheritProperty::theUI->NXMessageBox()->Show("Block Styler", NXOpen::NXMessageBox::DialogTypeError, ex.what());
    }
    return errorCode;
}

//------------------------------------------------------------------------------
//Function Name: GetBlockProperties
//Description: Returns the propertylist of the specified BlockID
//------------------------------------------------------------------------------
PropertyList* inheritProperty::GetBlockProperties(const char *blockID)
{
    return theDialog->GetBlockProperties(blockID);
}
