//==============================================================================
//  WARNING!!  This file is overwritten by the Block Styler while generating
//  the automation code. Any modifications to this file will be lost after
//  generating the code again.
//
//       Filename:  C:\codeguangzhou\install\application\Property.hpp
//
//        This file was generated by the NX Block Styler
//        Created by: Administrator
//              Version: NX 10
//              Date: 03-18-2019  (Format: mm-dd-yyyy)
//              Time: 19:52
//
//==============================================================================

#ifndef PROPERTY_H_INCLUDED
#define PROPERTY_H_INCLUDED

//------------------------------------------------------------------------------
//These includes are needed for the following template code
//------------------------------------------------------------------------------
#include <uf_defs.h>
#include <uf_ui_types.h>
#include <uf_modl.h>
#include <iostream>
#include <NXOpen/Session.hxx>
#include <NXOpen/UI.hxx>
#include <NXOpen/NXMessageBox.hxx>
#include <NXOpen/Callback.hxx>
#include <NXOpen/NXException.hxx>
#include <NXOpen/BlockStyler_UIBlock.hxx>
#include <NXOpen/BlockStyler_BlockDialog.hxx>
#include <NXOpen/BlockStyler_PropertyList.hxx>
#include <NXOpen/BlockStyler_Group.hxx>
#include <NXOpen/BlockStyler_MultilineString.hxx>
#include <NXOpen/BlockStyler_Enumeration.hxx>
#include <NXOpen/BlockStyler_BodyCollector.hxx>
#include <NXOpen/BlockStyler_SpecifyCSYS.hxx>
#include <NXOpen/BlockStyler_Button.hxx>
#include <NXOpen/BlockStyler_DoubleBlock.hxx>
#include <NXOpen/BlockStyler_Toggle.hxx>
#include "Common_Function.h"
//------------------------------------------------------------------------------
//Bit Option for Property: EntityType
//------------------------------------------------------------------------------
#define                         EntityType_AllowBodies (1 << 6);
//------------------------------------------------------------------------------
//Bit Option for Property: BodyRules
//------------------------------------------------------------------------------
#define                           BodyRules_SingleBody (1 << 0);
#define                        BodyRules_FeatureBodies (1 << 1);
#define                        BodyRules_BodiesinGroup (1 << 2);
//------------------------------------------------------------------------------
// Namespaces needed for following template
//------------------------------------------------------------------------------
using namespace std;
using namespace NXOpen;
using namespace NXOpen::BlockStyler;

class DllExport Property
{
    // class members
public:
    static Session *theSession;
    static UI *theUI;
    Property();
    ~Property();
    int Show();
    
    //----------------------- BlockStyler Callback Prototypes ---------------------
    // The following member function prototypes define the callbacks 
    // specified in your BlockStyler dialog.  The empty implementation
    // of these prototypes is provided in the Property.cpp file. 
    // You are REQUIRED to write the implementation for these functions.
    //------------------------------------------------------------------------------
    void initialize_cb();
    void dialogShown_cb();
    int apply_cb();
    int ok_cb();
    int update_cb(NXOpen::BlockStyler::UIBlock* block);
    int filter_cb(NXOpen::BlockStyler::UIBlock*  block, NXOpen::TaggedObject* selectObject);
    void focusNotify_cb(NXOpen::BlockStyler::UIBlock* block, bool focus);
    PropertyList* GetBlockProperties(const char *blockID);
    
private:
    const char* theDlxFileName;
    NXOpen::BlockStyler::BlockDialog* theDialog;
    NXOpen::BlockStyler::Group* group;// Block type: Group
    NXOpen::BlockStyler::MultilineString* str_techReq;// Block type: Multiline String
    NXOpen::BlockStyler::Group* group3;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enumType;// Block type: Enumeration
    NXOpen::BlockStyler::BodyCollector* bodySelect0;// Block type: Body Collector
    NXOpen::BlockStyler::Group* group1;// Block type: Group
    NXOpen::BlockStyler::Enumeration* enum09;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* enum08;// Block type: Enumeration
    NXOpen::BlockStyler::SpecifyCSYS* coord_system0;// Block type: Specify Csys
    NXOpen::BlockStyler::Button* buttonCalculate;// Block type: Button
    NXOpen::BlockStyler::DoubleBlock* bodyLen;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* bodyWidth;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* bodyarea;// Block type: Double
    NXOpen::BlockStyler::Group* group0;// Block type: Group
    NXOpen::BlockStyler::Enumeration* matName;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* matNO;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* matSize;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* material;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* matDensity;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* unitPrice;// Block type: Enumeration
    NXOpen::BlockStyler::Enumeration* supplier;// Block type: Enumeration
    NXOpen::BlockStyler::DoubleBlock* weight;// Block type: Double
    NXOpen::BlockStyler::DoubleBlock* totalPrice;// Block type: Double
    NXOpen::BlockStyler::Enumeration* remark;// Block type: Enumeration
    NXOpen::BlockStyler::Toggle* toggleoutNO;// Block type: Toggle
    NXOpen::BlockStyler::Group* group4;// Block type: Group
    NXOpen::BlockStyler::SpecifyCSYS* coord_system01;// Block type: Specify Csys
    NXOpen::BlockStyler::Group* group2;// Block type: Group
    NXOpen::BlockStyler::Toggle* hideBody;// Block type: Toggle
    NXOpen::BlockStyler::Enumeration* enum011;// Block type: Enumeration
    NXOpen::BlockStyler::Toggle* inheriteFrombody;// Block type: Toggle
    NXOpen::BlockStyler::BodyCollector* selectFrombody;// Block type: Body Collector
    NXOpen::BlockStyler::Button* buttonHideBody;// Block type: Button
    int SetBodyBoundingBoxSize( );
};
void GZ_PART_ATTR_Main();
#endif //PROPERTY_H_INCLUDED
